### ISSUE TITLE
NoClassDefFoundError: MetricWriteHelperFactory

### ISSUE THREAD

**Issue by gudzenkov** [Appdynamics/process-monitoring-extension#5] opened 2017-10-20 23:39 UTC
Monitor initialization fails with below exception.
Cannot find which lib provides MetricWriteHelperFactory class.
Please advise on the fix

```
Agent-Monitor-Scheduler-2] 20 Oct 2017 19:29:25,413 ERROR PeriodicTaskRunner - Error creating environment task
java.lang.NoClassDefFoundError: com/appdynamics/extensions/util/MetricWriteHelperFactory
        at com.appdynamics.monitors.nginx.NGinXMonitor.initialize(NGinXMonitor.java:32)
        at com.appdynamics.monitors.nginx.NGinXMonitor.execute(NGinXMonitor.java:62)
        at com.singularity.ee.agent.systemagent.components.monitormanager.managed.MonitorTaskRunner.runTask(MonitorTaskRunner.java:148)
```

**Comment by BalakrishnaV** [comment] 2017-10-21 05:30
Hi,

The error you observe is related to the https://github.com/Appdynamics/nginx-monitoring-extension project. We have checked in the fix for the issue now. Please try rebuilding the Nginx extension project and let us know in case of any issues.

If the issue is resolved, please close this issue.

Thanks

**Comment by gudzenkov** [comment] 2017-10-24 20:45
Hi,
Appreciate your fix for nginx-monitoring-extension, that worked!

**Closed as completed** 2017-10-24 20:46 UTC
